"""Add currency to Accounts Table

Revision ID: ae659e03e4b8
Revises: bc41877726e9
Create Date: 2026-07-20 16:12:57.499817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae659e03e4b8'
down_revision: Union[str, Sequence[str], None] = 'bc41877726e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('currency', sa.String(length=3), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'currency')
    # ### end Alembic commands ###
