"""Add account_type to Accounts Table

Revision ID: bc41877726e9
Revises: bf65cd9f5757
Create Date: 2026-07-20 15:59:04.706006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc41877726e9'
down_revision: Union[str, Sequence[str], None] = 'bf65cd9f5757'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('account_type', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'account_type')
    # ### end Alembic commands ###
