"""Add is_archived to Accounts Table

Revision ID: bf65cd9f5757
Revises: a5ab5d9bfdd7
Create Date: 2026-07-20 15:21:10.132771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf65cd9f5757'
down_revision: Union[str, Sequence[str], None] = 'a5ab5d9bfdd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('is_archived', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'is_archived')
    # ### end Alembic commands ###
